Increase hbase.hregion.memstore.flush.size in HBase conf to avoid test errors
Adjust hbase.hregion.memstore.flush.size in tests to avoid HBase
complaints like this:
setUp(com.yahoo.omid.transaction.TestUpdateScan):
org.apache.hadoop.hbase.DoNotRetryIOException: MEMSTORE_FLUSHSIZE for
table descriptor or hbase.hregion.memstore.flush.size (102400) is too
small, which might cause very frequent flushing. Set
hbase.table.sanity.checks to false at conf or table descriptor if you
want to bypass sanity checks

Change-Id: I2861e42360aa52e05f999c6f1bc262f37da9f837