[SLINGCSCF-2005] Set initial open-source version to 0.8.0
Also fix hbase version

&

Adjust hbase.hregion.memstore.flush.size in tests to avoid HBase
complaints like this:
setUp(com.yahoo.omid.transaction.TestUpdateScan):
org.apache.hadoop.hbase.DoNotRetryIOException: MEMSTORE_FLUSHSIZE for
table descriptor or "hbase.hregion.memstore.flush.size" (102400) is too
small, which might cause very frequent flushing. Set
hbase.table.sanity.checks to false at conf or table descriptor if you
want to bypass sanity checks

Change-Id: I8b5183a33f032385eed9e07e5d04d02dd7e8c1ba